apiVersion: flagger.app/v1alpha3
kind: Canary
metadata:
  name: machineinfo-app
  namespace: machineinfo
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: machineinfo-app
  service:
    port: 9000
  canaryAnalysis:
    interval: 1s
    threshold: 1
    stepWeight: 10
    metrics:
    - name: request-success-rate
      threshold: 10
      interval: 1s
