apiVersion: apps/v1
kind: Deployment
metadata:
  name: machineinfo-deploymentv1
  labels:
    app: machineinfo-app
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: machineinfo-app
      version: v1
  template:
    metadata:
      labels:
        app: machineinfo-app
        version: v1
    spec:
      containers:
        - name: machineinfo-container
          image: nehashirsat/devops_repo:v1.1.0
          ports:
            - containerPort: 9000
