apiVersion: apps/v1
kind: Deployment
metadata:
  name: machineinfo-deploymentv2
  labels:
    app: machineinfo-app2
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: machineinfo-app2
  template:
    metadata:
      labels:
        app: machineinfo-app
        version: v2
    spec:
      containers:
        - name: machineinfo-container
          image: nehashirsat/machineinfopink:v1.1.1
          ports:
            - containerPort: 9000
